
pipeline {
    agent {
        node {
            label 'Agent'
        }
    }
    options {
        ansiColor('xterm') //To get some colourful output. we need to install the AnsiColor plugin.
    }
    parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    // build
    stages {
        stage('Init') {
            steps {
                sh """
                    cd 01_vpc
                    terraform init -reconfigure
                """
            }
        }
        stage('Plan') {
            steps {
                sh """
                    cd 01_vpc
                    terraform plan
                """
            }
        }
        stage('Deploy') {
            when {
                expression { 
                    params.action == 'apply'
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh """
                    cd 01_vpc
                    terraform apply -auto-approve
                """
            }
        }
        stage('Destroy') {
            when {
                expression { 
                    params.action == 'destroy'
                }
            }
            input { //Input option asks for confirmation before it run terrafrom deploy command.
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh """
                    cd 01_vpc
                    terraform destroy -auto-approve
                """
            }
        }
    }
}